import { SoftwarePackage } from '@stencila/schema'
import path from 'path'

import PackageGenerator from './PackageGenerator'
import PythonSystemPackageLookup from './PythonSystemPackageLookup'
import UrlFetcher from './IUrlFetcher'

/**
 * A Dockerfile generator for Python packages
 */
export default class PythonGenerator extends PackageGenerator {
  /**
   * The Python Major version, i.e. 2 or 3
   */
  private readonly pythonMajorVersion: number

  /**
   * An instance of `PythonSystemPackageLookup` with which to look up system dependencies of Python packages
   */
  private readonly systemPackageLookup: PythonSystemPackageLookup

  // Methods that override those in `Generator`

  constructor(
    urlFetcher: UrlFetcher,
    pkg: SoftwarePackage,
    folder?: string,
    pythonMajorVersion = 3
  ) {
    super(urlFetcher, pkg, folder)

    this.pythonMajorVersion = pythonMajorVersion
    this.systemPackageLookup = PythonSystemPackageLookup.fromFile(
      path.join(__dirname, 'PythonSystemDependencies.json')
    )
  }

  /**
   * Return the `pythonMajorVersion` (as string) if it is not 2, otherwise return an empty string (if it is 2). This is
   * for appending to things like pip{3} or python{3}.
   */
  pythonVersionSuffix(): string {
    return this.pythonMajorVersion === 2 ? '' : `${this.pythonMajorVersion}`
  }

  /**
   * Check if this Generator's package applies (if it is Python).
   */
  applies(): boolean {
    return this.package.runtimePlatform === 'Python'
  }

  /**
   * Generate a list of system (apt) packages by looking up with `this.systemPackageLookup`.
   */
  aptPackages(sysVersion: string): Array<string> {
    let aptRequirements: Array<string> = []

    this.package.softwareRequirements.map((requirement) => {
      aptRequirements = aptRequirements.concat(
        this.systemPackageLookup.lookupSystemPackage(
          requirement.name,
          this.pythonMajorVersion,
          'deb',
          sysVersion
        )
      )
    })

    const dedupedRequirements: Array<string> = []
    aptRequirements.map((aptRequirement) => {
      if (!dedupedRequirements.includes(aptRequirement)) {
        dedupedRequirements.push(aptRequirement)
      }
    })
    return [
      `python${this.pythonVersionSuffix()}`,
      `python${this.pythonVersionSuffix()}-pip`,
    ].concat(dedupedRequirements)
  }

  /**
   * Get the pip command to install the Stencila package
   */
  stencilaInstall(sysVersion: string): string | undefined {
    return `pip${this.pythonVersionSuffix()} install --no-cache-dir https://github.com/stencila/py/archive/91a05a139ac120a89fc001d9d267989f062ad374.zip \\
 && python${this.pythonVersionSuffix()} -m stencila register`
  }

  /**
   * Write out the generated requirements content to `GENERATED_REQUIREMENTS_FILE` or none exists, just instruct the
   * copy of a `requirements.txt` file as part of the Dockerfile. If that does not exist, then no COPY should be done.
   */
  installFiles(sysVersion: string): Array<[string, string]> {
    if (this.exists('requirements.txt')) {
      return [['requirements.txt', 'requirements.txt']]
    }

    const packages = this.filterPackages('Python')
    if (packages.length === 0) return []

    this.write(
      '.requirements.txt',
      `# Generated by Dockta at ${new Date().toISOString()}.
# To stop Dockta generating this file and start editing it yourself, rename it to "requirements.txt".

` +
        packages
          .map((requirement) => `${requirement.name}${requirement.version}`)
          .join('\n')
    )
    return [['.requirements.txt', 'requirements.txt']]
  }

  /**
   * Generate the right pip command to install the requirements, appends the correct Python major version to `pip`.
   */
  installCommand(sysVersion: string): string | undefined {
    return `pip${this.pythonVersionSuffix()} install --requirement requirements.txt`
  }

  /**
   * The files to copy into the Docker image
   *
   * Copies all `*.py` files to the container
   */
  projectFiles(): Array<[string, string]> {
    const pyFiles = this.glob('**/*.py')
    return pyFiles.map((file) => [file, file])
  }

  runCommand(): string | undefined {
    if (this.exists('main.py'))
      return `python${this.pythonVersionSuffix()} main.py`
  }
}
