FROM ubuntu:16.04

ENV TZ="Etc/UTC" \
    R_LIBS_USER="~/R"

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      apt-transport-https \
      ca-certificates \
      software-properties-common

RUN apt-add-repository "deb https://mran.microsoft.com/snapshot/2018-10-29/bin/linux/ubuntu xenial/" \
 && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      libcurl4-openssl-dev \
      libssl-dev \
      make \
      python3 \
      python3-pip \
      r-base \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir https://github.com/stencila/py/archive/91a05a139ac120a89fc001d9d267989f062ad374.zip \
 && apt-get update \
 && apt-get install -y  zlib1g-dev libxml2-dev pkg-config \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && Rscript -e 'install.packages("devtools")' \
 && Rscript -e 'source("https://bioconductor.org/biocLite.R"); biocLite("graph")' \
 && Rscript -e 'devtools::install_github("r-lib/pkgbuild")' \
 && Rscript -e 'devtools::install_github("stencila/r")'

RUN useradd --create-home --uid 1001 -s /bin/bash dockteruser
USER dockteruser
WORKDIR /home/dockteruser

# dockter

COPY requirements.txt requirements.txt
COPY .DESCRIPTION DESCRIPTION

RUN pip3 install --user --requirement requirements.txt \
 && mkdir ~/R \
 && bash -c "Rscript <(curl -sL https://unpkg.com/@stencila/dockter/src/install.R)"

COPY script.R script.R

CMD Rscript script.R
