FROM ubuntu:16.04

ENV TZ="Etc/UTC" \
    R_LIBS_USER="~/R"

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      software-properties-common

RUN apt-add-repository "deb https://deb.nodesource.com/node_10.x xenial main" \
 && apt-add-repository "deb https://mran.microsoft.com/snapshot/2018-11-01/bin/linux/ubuntu xenial/"
RUN curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - \
 && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      libcurl4-openssl-dev \
      libssl-dev \
      make \
      nodejs \
      r-base \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN npm install stencila-node@0.28.15 \
 && apt-get update \
 && apt-get install -y  zlib1g-dev libxml2-dev pkg-config \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && Rscript -e 'install.packages("devtools")' \
 && Rscript -e 'source("https://bioconductor.org/biocLite.R"); biocLite("graph")' \
 && Rscript -e 'devtools::install_github("r-lib/pkgbuild")' \
 && Rscript -e 'devtools::install_github("stencila/r")'

RUN useradd --create-home --uid 1001 -s /bin/bash dockteruser
USER dockteruser
WORKDIR /home/dockteruser

# dockter

COPY .package.json package.json
COPY .DESCRIPTION DESCRIPTION

RUN npm install package.json \
 && mkdir ~/R \
 && bash -c "Rscript <(curl -sL https://unpkg.com/@stencila/dockter/src/install.R)"

COPY script.R script.R

CMD Rscript script.R
